version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_DSN=root:Bixilong5201!@tcp(mysql:3306)/chat_app?charset=utf8mb4&parseTime=True&loc=Local
      - REDIS_ADDR=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Bixilong5201!
      MYSQL_DATABASE: chat_app
    volumes:
      - mysql-data:/var/lib/mysql  # 持久化卷
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis:7.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
  rabbitmq:
    image: rabbitmq:3.13-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 15
volumes:
  mysql-data:  # 定义命名卷